version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8089:8089"
    environment:
      - MONGODB_URI=mongodb+srv://rodrigo:YHzLdkuvhwHQ8ZUZ@cluster0.bbqnvc3.mongodb.net/comp3123_assigment1?retryWrites=true&w=majority
      - MONGODB_USERNAME=rodrigo
      - MONGODB_PASSWORD=YHzLdkuvhwHQ8ZUZ
    networks:
      - assignment2

  frontend:
    build: ./101342857_comp3123_assignment2_reactjs
    ports:
      - "3000:3000"
    networks:
      - assignment2
